//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class campeonatos
    {
        public campeonatos()
        {
            this.partidos = new HashSet<partidos>();
            this.equipos1 = new HashSet<equipos>();
        }
    
        public int id_campeonato { get; set; }
        public int anio_campeonato { get; set; }
        public int cantidad_equipos { get; set; }
        public Nullable<int> id_equipo_campeon { get; set; }
    
        public virtual equipos equipos { get; set; }
        public virtual ICollection<partidos> partidos { get; set; }
        public virtual ICollection<equipos> equipos1 { get; set; }
    }
}
