//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GranFranciscanoEntities : DbContext
    {
        public GranFranciscanoEntities()
            : base("name=GranFranciscanoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<campeonatos> campeonatos { get; set; }
        public DbSet<equipos> equipos { get; set; }
        public DbSet<partidos> partidos { get; set; }
        public DbSet<preguntas> preguntas { get; set; }
        public DbSet<tipo_partidos> tipo_partidos { get; set; }
        public DbSet<tipo_usuarios> tipo_usuarios { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
    }
}
