//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class partidos
    {
        public partidos()
        {
            this.partidos1 = new HashSet<partidos>();
            this.equipos = new HashSet<equipos>();
        }
    
        public int id_partido { get; set; }
        public Nullable<System.DateTime> fec_partido { get; set; }
        public int equipos_pasan { get; set; }
        public int id_tipo_partido { get; set; }
        public int id_campeonato { get; set; }
        public Nullable<int> id_partido_padre { get; set; }
    
        public virtual campeonatos campeonatos { get; set; }
        public virtual ICollection<partidos> partidos1 { get; set; }
        public virtual partidos partidos2 { get; set; }
        public virtual tipo_partidos tipo_partidos { get; set; }
        public virtual ICollection<equipos> equipos { get; set; }
    }
}
