//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_usuarios
    {
        public tipo_usuarios()
        {
            this.usuarios = new HashSet<usuarios>();
        }
    
        public int id_tipo_usuario { get; set; }
        public string tipo_usuario { get; set; }
    
        public virtual ICollection<usuarios> usuarios { get; set; }
    }
}
