//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_partidos
    {
        public tipo_partidos()
        {
            this.partidos = new HashSet<partidos>();
        }
    
        public int id_tipo_partido { get; set; }
        public string tipo_partido { get; set; }
    
        public virtual ICollection<partidos> partidos { get; set; }
    }
}
