//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int id_usario { get; set; }
        public string nombre_usuario { get; set; }
        public string contrasenia { get; set; }
        public System.DateTime fec_registro { get; set; }
        public int id_tipo_usuario { get; set; }
    
        public virtual tipo_usuarios tipo_usuarios { get; set; }
    }
}
